
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: meniscus_development
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: meniscus_test
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

# production:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: fondak
#   pool: 5
#   username: root
#   password:
#   socket: /var/lib/mysql/mysql.sock
production:
  adapter: mysql2
  encoding: utf8
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  pool: 5
  host: <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port: <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>
  username: <%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>
  socket: <%=ENV['OPENSHIFT_MYSQL_DB_SOCKET']%>